### ISSUE TITLE
Prebuilt copies?

### ISSUE THREAD

**Issue by Wowfunhappy** [MrMarukesu/Flatpak-Elementary-Apps#1]
Has anyone managed to build these successfully, and would it be possible to share the flatpak bundles? I don't think there should be any legal issues in doing so?

Thank you!

**Comment by Marukesu** [comment]
Yes, i build them before push to repo.
About the bundles, since i'm updating the manifest to use the elementary sdk, it's not make much sense for me (since they doesn't have a bundle or a repo to install it).  
sorry for the super late resonse :)
